# Generated by Django 4.2.7 on 2023-12-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='albumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=100)),
                ('Album_release_date', models.DateField()),
                ('Rating_between', models.PositiveIntegerField(choices=[(5, '5'), (1, '1'), (3, '3'), (4, '4'), (2, '2')], default=5)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musicanmodel')),
            ],
        ),
    ]
