# Generated by Django 4.2.7 on 2023-12-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=100)),
                ('Album_relese_Date', models.DateTimeField(auto_now=True)),
                ('Rating_between', models.PositiveIntegerField(choices=[(3, '3'), (5, '5'), (2, '2'), (1, '1'), (4, '4')], default=5)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musican')),
            ],
        ),
    ]
